Vector overlay branch
Westview-USC-Biomechanics-Collaboration/Prepare2Play-Learning-Experience pull request #80
Opened 2024-07-31 01:09 UTC by Chase-520

vector overlay is ready to be merged to the main branch

2024-07-31 01:25 UTC, Yodaman07 approved these changes

2024-07-31 04:09 UTC, Yodaman07 approved these changes

2024-07-31 16:54 UTC, allison-lane requested changes
the videos and force files in the data folder should not be pushed to main, they are taking up unnecessary space

2024-08-01 00:37 UTC, allison-lane approved these changes

2024-08-01 00:37 UTC, merged